name: Segundo Workflow

on:
  push:

jobs:
  segundo-job:
    runs-on: ubuntu-latest
    env:
      CURSO: "Integração Contínua"
    steps:
      - name: Primeiro passo
        run: echo "Segundo passo"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Lista de arquivos
        run: ls ${{ github.workspace }}

      
      - name: Exibir data e hora da execução
        run: date

      - name: Exibir sistema operacional do runner
        run: uname -a

      - name: Exibir versão do Git
        run: git --version

      - name: Exibir conteúdo do arquivo README.md
        run: cat README.md

      - name: Listar arquivos do projeto novamente
        run: ls -la
