name: Terceiro Workflow

on:
  push:

jobs:
  segundo-job:
    runs-on: ubuntu-latest
    env:
      CURSO: "Integração Contínua"
    steps:
      - name: Primeiro passo
        run: echo "Segundo passo"

      - name: Checkout
        uses: actions/checkout@v5

      - name: Lista de arquivos
        run: ls ${{ github.workspace }}

      - name: Exibir informações do workflow
        run: |
          echo "Nome do curso: $CURSO"
          echo "Usuário que executou o workflow: ${{ github.actor }}"
          echo "Nome do repositório: ${{ github.repository }}"
          echo "Branch utilizada: ${{ github.ref_name }}"
          echo "Status do job: ${{ job.status }}."

     

